name: Compile MEX
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cpp'
      - '**/*.hpp'

jobs:
  compile_mex:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15-intel, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            os_name: Linux
            mex_ext: mexa64
          - os: macos-15-intel
            os_name: macOS_Intel
            mex_ext: mexmaci64
          - os: macos-latest
            os_name: macOS_Apple_Silicon
            mex_ext: mexmaca64
          - os: windows-latest
            os_name: Windows
            mex_ext: mexw64

    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Checkout SPM
        uses: actions/checkout@v4

      - name: Delete old MEX files on Ubuntu and Mac
        if: matrix.os != 'windows-latest'
        run: find . -type f -name "*.mex*" -delete

      - name: Delete old MEX files on Windows
        if: matrix.os == 'windows-latest'
        run: Get-ChildItem -Path .\ -Recurse -Include *.mex* | Remove-Item -Force

      - name: Compile MEX files
        run: |
          make -C src distclean
          make -C src
          make -C src install
          # make -C src external-distclean # on windows there is an issue with fieldtrip
          # make -C src external
          # make -C src external-install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spm-mex-${{ matrix.os_name }}
          path: ./**/*.${{ matrix.mex_ext }}
          retention-days: 1

  collect_mex_files:
    runs-on: ubuntu-latest
    needs: compile_mex
    steps:
      - name: Download all MEX artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: spm-mex-*
          merge-multiple: true

      - name: Upload all mex files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spm-mex-all
          path: .
